# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='status',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Group'),
        ),
    ]
