# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20170217_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Group', verbose_name=b'Category'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.CharField(max_length=128, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='source',
            field=models.CharField(max_length=64, verbose_name=b'File'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'Name'),
        ),
    ]
