# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20170220_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='source',
            field=models.FileField(blank=True, upload_to=b'audios/', verbose_name=b'File'),
        ),
    ]
