# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('introduction', models.TextField()),
                ('status', models.BooleanField()),
                ('price', models.FloatField()),
                ('alarm_time', models.IntegerField()),
                ('alarm_duration', models.IntegerField()),
                ('alarm_repetition', models.IntegerField()),
                ('android_code', models.CharField(max_length=64)),
                ('ios_code', models.CharField(max_length=64)),
                ('alarm_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_sound', to='audio.Audio')),
                ('dream_sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_sound', to='audio.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('duration', models.IntegerField()),
                ('image_source', models.CharField(max_length=64)),
                ('image_repetition', models.IntegerField()),
                ('text', models.CharField(max_length=128)),
                ('text_repetition', models.IntegerField()),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Dream')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='dream',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Group'),
        ),
    ]
