# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0005_auto_20170217_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='groups',
            field=models.ManyToManyField(blank=True, to='dream.Group', verbose_name=b'Categories'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='alarm_duration',
            field=models.IntegerField(verbose_name=b'Alarm Duration(sec)'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='alarm_repetition',
            field=models.IntegerField(verbose_name=b'Alarm Repetitions'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='alarm_sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_sound', to='audio.Audio', verbose_name=b'Alarm Sound'),
        ),
        # migrations.AlterField(
        #     model_name='dream',
        #     name='alarm_time',
        #     field=models.TimeField(verbose_name=b'Alarm Time(min)'),
        # ),
        migrations.AlterField(
            model_name='dream',
            name='android_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Android Code'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='description',
            field=models.CharField(max_length=128, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='dream_sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_sound', to='audio.Audio', verbose_name=b'Background Sound'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Group', verbose_name=b'Category'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='introduction',
            field=models.TextField(verbose_name=b'Introduction'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='ios_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'IOS Code'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='dream',
            name='price',
            field=models.FloatField(verbose_name=b'Price'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dream.Dream', verbose_name=b'Dream'),
        ),
        # migrations.AlterField(
        #     model_name='frame',
        #     name='duration',
        #     field=models.TimeField(verbose_name=b'Frame Duration(sec)'),
        # ),
        migrations.AlterField(
            model_name='frame',
            name='image_repetition',
            field=models.IntegerField(verbose_name=b'Image Repetitions'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='image_source',
            field=models.CharField(max_length=64, verbose_name=b'Image Source'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='text',
            field=models.CharField(max_length=128, verbose_name=b'Text'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='text_repetition',
            field=models.IntegerField(verbose_name=b'Text Repetitions'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream.Group', verbose_name=b'Parent'),
        ),
        migrations.AlterField(
            model_name='library',
            name='dream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream.Dream', verbose_name=b'Dream'),
        ),
        migrations.AlterField(
            model_name='library',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream.Pack', verbose_name=b'Pack'),
        ),
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='android_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'Android Code'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.CharField(max_length=128, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='dreams',
            field=models.ManyToManyField(blank=True, to='dream.Dream', verbose_name=b'Dreams'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='ios_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name=b'IOS Code'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(max_length=64, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='price',
            field=models.FloatField(verbose_name=b'Price'),
        ),
    ]
