# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0006_auto_20170218_1915'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='dream',
        #     name='alarm_time',
        #     field=models.IntegerField(verbose_name=b'Alarm Time(min)'),
        # ),
    ]
