# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0007_auto_20170220_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='alarm_time',
            field=models.IntegerField(verbose_name=b'Alarm Time(min)'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='duration',
            field=models.IntegerField(verbose_name=b'Frame Duration(sec)'),
        ),
    ]
