# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0008_auto_20170220_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='dreams',
            field=models.ManyToManyField(blank=True, related_name='packs_dreams', to='dream.Dream', verbose_name=b'Dreams'),
        ),
    ]
