# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0012_auto_20170302_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='cover_page',
            field=models.CharField(blank=True, max_length=128, verbose_name=b'Cover Page'),
        ),
    ]
