# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0013_dream_cover_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='cover_page',
            field=models.FileField(blank=True, upload_to=b'cover_pages/', verbose_name=b'Cover Page'),
        ),
    ]
