# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0006_auto_20170218_1915'),
        ('shoppingcar', '0002_auto_20170217_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcar.Coupon', verbose_name=b'Coupon Used'),
        ),
        migrations.AddField(
            model_name='order',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream.Pack', verbose_name=b'Pack'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='all_products_available',
            field=models.BooleanField(default=False, verbose_name=b'All Products are Available'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='categories',
            field=models.ManyToManyField(to='dream.Group', verbose_name=b'Categories'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(max_length=64, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='dreams',
            field=models.ManyToManyField(to='dream.Dream', verbose_name=b'Dreams'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(verbose_name=b'Available until'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='fixed_discount',
            field=models.FloatField(verbose_name=b'Fixed Discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='packs',
            field=models.ManyToManyField(to='dream.Pack', verbose_name=b'Packs'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent_discount',
            field=models.FloatField(verbose_name=b'Percent Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, verbose_name=b'Discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dream.Dream', verbose_name=b'Dream'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcar.PaymentMethod', verbose_name=b'Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoppingcar.Plan', verbose_name=b'Plan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name=b'Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='api_key',
            field=models.CharField(max_length=128, verbose_name=b'API Key'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.CharField(max_length=64, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='password_auth',
            field=models.CharField(max_length=64, verbose_name=b'Password Authentication'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user_auth',
            field=models.CharField(max_length=32, verbose_name=b'Username Authentication'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=256, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=30, verbose_name=b'Duration(day)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name=b'Is Available'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(verbose_name=b'Price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Added on'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.FloatField(verbose_name=b'Value'),
        ),
        migrations.AlterField(
            model_name='usedcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcar.Coupon', verbose_name=b'Coupon'),
        ),
        migrations.AlterField(
            model_name='usedcoupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Used at'),
        ),
        migrations.AlterField(
            model_name='usedcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
